import * as core from './core-adapter.js';
import type { DocPage } from './types.js';
import type {
  SystemSpec,
  SubsystemSpec,
  ComponentSpec,
  InterfaceSpec,
} from '../models/index.js';

// ---------------------------------------------------------------------------
// Spec Projection Specialist (sdd_producers)
//
// Projects the bound project's spec tree into a target-agnostic DocPage tree:
// a "wairon specs" root (system overview + Mermaid + optional canvas link), a
// child page per subsystem, and a page per component with its methods. Pure —
// no I/O beyond the core loaders, so it's unit-testable.
// ---------------------------------------------------------------------------

export function project(diagramUrl: string): DocPage {
  const system = core.loadSystemSpec();
  const subsystems = core.loadSubsystemSpecs();
  const components = core.loadComponentSpecs();
  const interfaces = core.loadInterfaceSpecs();

  let mermaid = '';
  try {
    mermaid = core.renderDiagram('mermaid');
  } catch {
    /* no components yet */
  }

  return {
    title: 'wairon specs',
    body: systemBody(system, mermaid, diagramUrl),
    children: subsystems.map((sub) => ({
      title: sub.name || sub.id,
      body: subsystemBody(sub),
      children: components
        .filter((c) => c.subsystem === sub.id)
        .map((comp) => ({
          title: `${comp.name || comp.id} (${comp.componentType})`,
          body: componentBody(comp, interfaces),
          children: [],
        })),
    })),
  };
}

function systemBody(system: SystemSpec | null, mermaid: string, diagramUrl: string): string {
  const parts = ['_Generated by wairon from the spec tree — edit the specs, not this page._', ''];
  if (system) {
    parts.push(`# ${system.name}`, '');
    if (system.vision) parts.push(system.vision, '');
    if (system.boundaries?.length) {
      parts.push('## Boundaries', ...system.boundaries.map((b) => `- ${typeof b === 'string' ? b : b.name}`), '');
    }
  }
  if (diagramUrl) parts.push('## Diagram', `[Open the interactive canvas](${diagramUrl})`, '');
  if (mermaid) parts.push('```mermaid', mermaid.trim(), '```', '');
  return parts.join('\n');
}

function subsystemBody(sub: SubsystemSpec): string {
  const parts = [`# ${sub.name || sub.id}`, ''];
  if (sub.description) parts.push(sub.description, '');
  if (sub.publicInterfaces?.length) {
    parts.push('## Public surface');
    for (const p of sub.publicInterfaces) parts.push(`- **${p.type}** via \`${p.component ?? '?'}\` — ${p.details}`);
    parts.push('');
  }
  return parts.join('\n');
}

function componentBody(comp: ComponentSpec, interfaces: InterfaceSpec[]): string {
  const parts = [`# ${comp.name || comp.id}`, '', `**Type:** ${comp.componentType}`, ''];
  if (comp.description) parts.push(comp.description, '');
  if (comp.owns?.length) parts.push(`**Owns:** ${comp.owns.join(', ')}`, '');
  if (comp.dependsOn?.length) parts.push(`**Depends on:** ${comp.dependsOn.join(', ')}`, '');
  const intf = interfaces.find((i) => i.component === comp.id);
  if (intf?.methods?.length) {
    parts.push('## Methods');
    for (const m of intf.methods) parts.push(`- **${m.name}** \`${m.signature}\` → ${m.returns}`);
    parts.push('');
  }
  return parts.join('\n');
}
