/**
 * Structural code↔spec conformance (Level 1) — src/core/rules/conformance.ts.
 *
 * Documented intents pinned here (rule description + doc comments + the
 * ConformanceTierSchema doc in src/models/specs.ts):
 *  - MISSING_SOURCE_PATH (warning): an implementation declares no sourcePath,
 *    so its contract cannot be structurally linked to code. An
 *    `implementation`-type externalLink on the component is the external
 *    source-of-record and suppresses the finding.
 *  - MISSING_SOURCE_FILE (error): an L4 sourcePath does not resolve to a file
 *    on disk — the spec names code that does not exist.
 *  - SOURCE_PATH_ESCAPES_ROOT (error): an L4 sourcePath is absolute or
 *    escapes the project root (containment refusal).
 *  - UNREALIZED_METHOD (warning): an L3 contract method has no anchor in the
 *    implementation's source file at the required conformance tier.
 *    `declared` needs a declaration-tier anchor; `anchored` (the Portal
 *    stereotype default) also accepts exact string-literal occurrences;
 *    `off` skips method checks; a per-method `symbol` maps the intent-language
 *    contract name to the code-level name and is authoritative when given.
 *  - CONFORMANCE_ANALYSIS_SKIPPED (warning): a sourcePath file is binary or
 *    unreadable — method realization was not checked.
 *  - CONFORMANCE_DEGRADED (warning): TypeScript/JavaScript files were
 *    analyzed below exact grade — structural findings stay honest via their
 *    grade, but dependency conformance skips those files. (In this test
 *    environment the compiler is always resolvable, so the below-exact grade
 *    is produced the other documented way: "a single file's failure degrades
 *    that file, never the run" — a generated file the parser cannot handle
 *    falls back to the generic word scan.)
 */
import { defineRuleFixture } from '../harness.js';

// A machine-generated decision-table module whose expression nesting exceeds
// the compiler front-end's recursion budget: exact AST analysis fails for this
// ONE file and honestly degrades to the generic word scan (grade: generic).
const NEST_DEPTH = 60000;
const GENERATED_FARE_MATRIX =
  '// AUTO-GENERATED by fare-matrix-compiler v3 — do not edit by hand.\n'
  + 'export const fareRuleMatrix = ' + '['.repeat(NEST_DEPTH) + '0' + ']'.repeat(NEST_DEPTH) + ';\n'
  + 'export function evaluateFareRules(): number { return 0; }\n';

export default [
  // -------------------------------------------------------------------------
  // MISSING_SOURCE_PATH
  // -------------------------------------------------------------------------
  defineRuleFixture({
    code: 'MISSING_SOURCE_PATH',
    severity: 'warning',
    anchoredTo: 'settlement_exporter_impl',
    expectFire: true,
    scenario:
      'The settlement exporter is fully specified down to narratives, but its implementation names no sourcePath, so the contract cannot be linked to any code.',
    tree: {
      subsystems: [{ id: 'billing', description: 'Invoicing and settlement export for completed orders.' }],
      components: [
        {
          id: 'settlement-exporter',
          componentType: 'Orchestrator',
          subsystem: 'billing',
          description: 'Assembles daily settlement batches and hands them to the bank file drop.',
        },
      ],
      interfaces: [
        {
          id: 'isettlement_exporter',
          component: 'settlement-exporter',
          methods: [{ name: 'exportSettlements', description: 'Assemble and export the daily settlement batch.' }],
        },
      ],
      implementations: [
        {
          id: 'settlement_exporter_impl',
          contract: 'isettlement_exporter',
          methods: [
            {
              name: 'exportSettlements',
              narrative: [{ stepNumber: 1, type: 'local', description: 'Collect the day\'s captured payments into a settlement batch.' }],
            },
          ],
        },
      ],
    },
  }),
  defineRuleFixture({
    code: 'MISSING_SOURCE_PATH',
    expectFire: false,
    reason:
      'An `implementation`-type externalLink is the documented external source-of-record: wairon cannot analyze it, so MISSING_SOURCE_PATH would be noise and is suppressed.',
    scenario:
      'The settlement exporter is realized as a Make.com scenario documented via an implementation-type external link, so the source-less implementation is sanctioned.',
    tree: {
      subsystems: [{ id: 'billing', description: 'Invoicing and settlement export for completed orders.' }],
      components: [
        {
          id: 'settlement-exporter',
          componentType: 'Orchestrator',
          subsystem: 'billing',
          description: 'Assembles daily settlement batches and hands them to the bank file drop.',
          externalLinks: [
            { url: 'https://eu1.make.com/scenarios/settlement-export', type: 'implementation', label: 'Make.com settlement export scenario' },
          ],
        },
      ],
      interfaces: [
        {
          id: 'isettlement_exporter',
          component: 'settlement-exporter',
          methods: [{ name: 'exportSettlements', description: 'Assemble and export the daily settlement batch.' }],
        },
      ],
      implementations: [
        {
          id: 'settlement_exporter_impl',
          contract: 'isettlement_exporter',
          methods: [
            {
              name: 'exportSettlements',
              narrative: [{ stepNumber: 1, type: 'local', description: 'Collect the day\'s captured payments into a settlement batch.' }],
            },
          ],
        },
      ],
    },
  }),

  // -------------------------------------------------------------------------
  // MISSING_SOURCE_FILE
  // -------------------------------------------------------------------------
  defineRuleFixture({
    code: 'MISSING_SOURCE_FILE',
    severity: 'error',
    anchoredTo: 'invoicing_engine_impl',
    expectFire: true,
    scenario:
      'The invoicing engine implementation points at src/billing/invoicing.ts, but the module was deleted in a cleanup and the spec now names code that does not exist.',
    tree: {
      subsystems: [{ id: 'billing', description: 'Invoicing and payment collection for placed orders.' }],
      components: [
        {
          id: 'invoicing-engine',
          componentType: 'Orchestrator',
          subsystem: 'billing',
          description: 'Turns completed orders into issued invoices.',
        },
      ],
      interfaces: [
        {
          id: 'iinvoicing_engine',
          component: 'invoicing-engine',
          methods: [{ name: 'generateInvoice', description: 'Assemble the line items and issue the invoice.' }],
        },
      ],
      implementations: [
        {
          id: 'invoicing_engine_impl',
          contract: 'iinvoicing_engine',
          sourcePath: 'src/billing/invoicing.ts',
          methods: [
            {
              name: 'generateInvoice',
              narrative: [{ stepNumber: 1, type: 'local', description: 'Assemble the order\'s line items into an invoice draft.' }],
            },
          ],
        },
      ],
      // deliberately NO src/billing/invoicing.ts on disk
      files: {},
    },
  }),
  defineRuleFixture({
    code: 'MISSING_SOURCE_FILE',
    expectFire: false,
    reason: 'The sourcePath resolves to a real committed module inside the project root.',
    scenario:
      'The invoicing engine implementation points at src/billing/invoicing.ts, which exists and declares the contract method.',
    tree: {
      subsystems: [{ id: 'billing', description: 'Invoicing and payment collection for placed orders.' }],
      components: [
        {
          id: 'invoicing-engine',
          componentType: 'Orchestrator',
          subsystem: 'billing',
          description: 'Turns completed orders into issued invoices.',
        },
      ],
      interfaces: [
        {
          id: 'iinvoicing_engine',
          component: 'invoicing-engine',
          methods: [{ name: 'generateInvoice', description: 'Assemble the line items and issue the invoice.' }],
        },
      ],
      implementations: [
        {
          id: 'invoicing_engine_impl',
          contract: 'iinvoicing_engine',
          sourcePath: 'src/billing/invoicing.ts',
          methods: [
            {
              name: 'generateInvoice',
              narrative: [{ stepNumber: 1, type: 'local', description: 'Assemble the order\'s line items into an invoice draft.' }],
            },
          ],
        },
      ],
      files: {
        'src/billing/invoicing.ts': [
          'export function generateInvoice(orderId: string): void {',
          '  // assemble line items and persist the issued invoice',
          '}',
          '',
        ].join('\n'),
      },
    },
  }),

  // -------------------------------------------------------------------------
  // SOURCE_PATH_ESCAPES_ROOT
  // -------------------------------------------------------------------------
  defineRuleFixture({
    code: 'SOURCE_PATH_ESCAPES_ROOT',
    severity: 'error',
    anchoredTo: 'rate_plan_engine_impl',
    expectFire: true,
    scenario:
      'The rate plan engine implementation reaches outside the repository into a sibling shared-kernel checkout via a parent-directory sourcePath, violating containment.',
    tree: {
      subsystems: [{ id: 'pricing', description: 'Tariff and rate plan computation for the storefront.' }],
      components: [
        {
          id: 'rate-plan-engine',
          componentType: 'Specialist',
          subsystem: 'pricing',
          description: 'Computes the applicable rate plan for a subscription.',
        },
      ],
      interfaces: [
        {
          id: 'irate_plan_engine',
          component: 'rate-plan-engine',
          methods: [{ name: 'resolveRatePlan', description: 'Pick the applicable rate plan for a subscription.' }],
        },
      ],
      implementations: [
        {
          id: 'rate_plan_engine_impl',
          contract: 'irate_plan_engine',
          sourcePath: '../shared-kernel/src/pricing/rate-plan.ts',
          methods: [
            {
              name: 'resolveRatePlan',
              narrative: [{ stepNumber: 1, type: 'local', description: 'Match the subscription against the tariff table.' }],
            },
          ],
        },
      ],
    },
  }),
  defineRuleFixture({
    code: 'SOURCE_PATH_ESCAPES_ROOT',
    expectFire: false,
    reason: 'The sourcePath is project-relative and stays inside the project root, which is the containment contract.',
    scenario:
      'The rate plan engine implementation points at the vendored copy of the pricing module inside the project tree.',
    tree: {
      subsystems: [{ id: 'pricing', description: 'Tariff and rate plan computation for the storefront.' }],
      components: [
        {
          id: 'rate-plan-engine',
          componentType: 'Specialist',
          subsystem: 'pricing',
          description: 'Computes the applicable rate plan for a subscription.',
        },
      ],
      interfaces: [
        {
          id: 'irate_plan_engine',
          component: 'rate-plan-engine',
          methods: [{ name: 'resolveRatePlan', description: 'Pick the applicable rate plan for a subscription.' }],
        },
      ],
      implementations: [
        {
          id: 'rate_plan_engine_impl',
          contract: 'irate_plan_engine',
          sourcePath: 'src/pricing/rate-plan.ts',
          methods: [
            {
              name: 'resolveRatePlan',
              narrative: [{ stepNumber: 1, type: 'local', description: 'Match the subscription against the tariff table.' }],
            },
          ],
        },
      ],
      files: {
        'src/pricing/rate-plan.ts': [
          'export function resolveRatePlan(subscriptionId: string): string {',
          '  return \'standard-monthly\';',
          '}',
          '',
        ].join('\n'),
      },
    },
  }),

  // -------------------------------------------------------------------------
  // UNREALIZED_METHOD — pair A: declared tier (non-Portal default), plain miss
  // -------------------------------------------------------------------------
  defineRuleFixture({
    code: 'UNREALIZED_METHOD',
    severity: 'warning',
    anchoredTo: 'rating_engine_impl',
    expectFire: true,
    scenario:
      'The rating engine contract promises compileRatePlan, but the module only ever grew the surcharge helper — the contract method has no declaration in the file.',
    tree: {
      subsystems: [{ id: 'billing', description: 'Rating and invoicing for metered usage.' }],
      components: [
        {
          id: 'rating-engine',
          componentType: 'Orchestrator',
          subsystem: 'billing',
          description: 'Compiles usage records into rated line items.',
        },
      ],
      interfaces: [
        {
          id: 'irating_engine',
          component: 'rating-engine',
          methods: [{ name: 'compileRatePlan', description: 'Compile the customer\'s usage into a rated plan.' }],
        },
      ],
      implementations: [
        {
          id: 'rating_engine_impl',
          contract: 'irating_engine',
          sourcePath: 'src/billing/rating-engine.ts',
          methods: [
            {
              name: 'compileRatePlan',
              narrative: [{ stepNumber: 1, type: 'local', description: 'Fold the usage records into rated line items.' }],
            },
          ],
        },
      ],
      files: {
        'src/billing/rating-engine.ts': [
          'export function applySurcharges(planTotal: number): number {',
          '  return planTotal * 1.21;',
          '}',
          '',
        ].join('\n'),
      },
    },
  }),
  defineRuleFixture({
    code: 'UNREALIZED_METHOD',
    expectFire: false,
    reason: 'The contract method is a named declaration in the sourcePath file, which satisfies the declared tier.',
    scenario:
      'The rating engine module declares compileRatePlan as an exported function, realizing the contract at the declared tier.',
    tree: {
      subsystems: [{ id: 'billing', description: 'Rating and invoicing for metered usage.' }],
      components: [
        {
          id: 'rating-engine',
          componentType: 'Orchestrator',
          subsystem: 'billing',
          description: 'Compiles usage records into rated line items.',
        },
      ],
      interfaces: [
        {
          id: 'irating_engine',
          component: 'rating-engine',
          methods: [{ name: 'compileRatePlan', description: 'Compile the customer\'s usage into a rated plan.' }],
        },
      ],
      implementations: [
        {
          id: 'rating_engine_impl',
          contract: 'irating_engine',
          sourcePath: 'src/billing/rating-engine.ts',
          methods: [
            {
              name: 'compileRatePlan',
              narrative: [{ stepNumber: 1, type: 'local', description: 'Fold the usage records into rated line items.' }],
            },
          ],
        },
      ],
      files: {
        'src/billing/rating-engine.ts': [
          'export function compileRatePlan(customerId: string): number {',
          '  return applySurcharges(0);',
          '}',
          '',
          'function applySurcharges(planTotal: number): number {',
          '  return planTotal * 1.21;',
          '}',
          '',
        ].join('\n'),
      },
    },
  }),

  // -------------------------------------------------------------------------
  // UNREALIZED_METHOD — pair B: a string-literal-only anchor is too weak for
  // the declared tier, but dialing the implementation to `anchored` accepts it
  // -------------------------------------------------------------------------
  defineRuleFixture({
    code: 'UNREALIZED_METHOD',
    severity: 'warning',
    anchoredTo: 'batch_job_runner_impl',
    expectFire: true,
    scenario:
      'The batch job runner registers compileRatePlan only as a command-table string key, which is a weak anchor — at the declared tier the contract method counts as unrealized.',
    tree: {
      subsystems: [{ id: 'billing', description: 'Rating and invoicing for metered usage.' }],
      components: [
        {
          id: 'batch-job-runner',
          componentType: 'Orchestrator',
          subsystem: 'billing',
          description: 'Runs nightly rating jobs from a registered command table.',
        },
      ],
      interfaces: [
        {
          id: 'ibatch_job_runner',
          component: 'batch-job-runner',
          methods: [{ name: 'compileRatePlan', description: 'Run the nightly rate plan compilation job.' }],
        },
      ],
      implementations: [
        {
          id: 'batch_job_runner_impl',
          contract: 'ibatch_job_runner',
          sourcePath: 'src/billing/batch-job-runner.ts',
          methods: [
            {
              name: 'compileRatePlan',
              narrative: [{ stepNumber: 1, type: 'local', description: 'Compile every active customer\'s usage into a rated plan.' }],
            },
          ],
        },
      ],
      files: {
        'src/billing/batch-job-runner.ts': [
          'const commandTable = new Map<string, () => void>();',
          '',
          'commandTable.set(\'compileRatePlan\', () => {',
          '  // handler body is bound lazily by the job scheduler',
          '});',
          '',
        ].join('\n'),
      },
    },
  }),
  defineRuleFixture({
    code: 'UNREALIZED_METHOD',
    expectFire: false,
    reason:
      'The implementation dials conformance to `anchored`, and the documented anchored tier accepts exact string-literal occurrences (tool/route registrations).',
    scenario:
      'The batch job runner registers compileRatePlan as a command-table string key and the implementation is dialed to the anchored conformance tier.',
    tree: {
      subsystems: [{ id: 'billing', description: 'Rating and invoicing for metered usage.' }],
      components: [
        {
          id: 'batch-job-runner',
          componentType: 'Orchestrator',
          subsystem: 'billing',
          description: 'Runs nightly rating jobs from a registered command table.',
        },
      ],
      interfaces: [
        {
          id: 'ibatch_job_runner',
          component: 'batch-job-runner',
          methods: [{ name: 'compileRatePlan', description: 'Run the nightly rate plan compilation job.' }],
        },
      ],
      implementations: [
        {
          id: 'batch_job_runner_impl',
          contract: 'ibatch_job_runner',
          sourcePath: 'src/billing/batch-job-runner.ts',
          conformance: 'anchored',
          methods: [
            {
              name: 'compileRatePlan',
              narrative: [{ stepNumber: 1, type: 'local', description: 'Compile every active customer\'s usage into a rated plan.' }],
            },
          ],
        },
      ],
      files: {
        'src/billing/batch-job-runner.ts': [
          'const commandTable = new Map<string, () => void>();',
          '',
          'commandTable.set(\'compileRatePlan\', () => {',
          '  // handler body is bound lazily by the job scheduler',
          '});',
          '',
        ].join('\n'),
      },
    },
  }),

  // -------------------------------------------------------------------------
  // UNREALIZED_METHOD — pair C: a per-method `symbol` override is
  // authoritative: the override must be realized, and it also realizes a
  // contract whose intent-language name never appears in code
  // -------------------------------------------------------------------------
  defineRuleFixture({
    code: 'UNREALIZED_METHOD',
    severity: 'warning',
    anchoredTo: 'snapshot_store_impl',
    expectFire: true,
    scenario:
      'The snapshot store maps persistSnapshot to the code name writeSnapshotRow via a per-method symbol, but the module only declares the legacy persistSnapshot shim — the mapped symbol is what must exist, and it does not.',
    tree: {
      subsystems: [{ id: 'reporting', description: 'Analytics snapshots for the merchant dashboard.' }],
      components: [
        {
          id: 'snapshot-store',
          componentType: 'Store',
          subsystem: 'reporting',
          durability: 'read-through',
          description: 'Holds the persisted analytics snapshots.',
        },
      ],
      interfaces: [
        {
          id: 'isnapshot_store',
          component: 'snapshot-store',
          methods: [{ name: 'persistSnapshot', description: 'Persist one analytics snapshot row.' }],
        },
      ],
      implementations: [
        {
          id: 'snapshot_store_impl',
          contract: 'isnapshot_store',
          sourcePath: 'src/reporting/snapshot-store.ts',
          methods: [
            {
              name: 'persistSnapshot',
              symbol: 'writeSnapshotRow',
              intent: 'Persist the snapshot row transactionally; on write failure the snapshot is dropped and the failure is surfaced to the caller.',
            },
          ],
        },
      ],
      files: {
        'src/reporting/snapshot-store.ts': [
          'export function persistSnapshot(payload: object): void {',
          '  // legacy shim retained for old call sites — the mapped writeSnapshotRow is gone',
          '}',
          '',
        ].join('\n'),
      },
    },
  }),
  defineRuleFixture({
    code: 'UNREALIZED_METHOD',
    expectFire: false,
    reason:
      'The per-method symbol maps the intent-language contract name to the real code name, and the mapped declaration exists — exactly the documented purpose of `symbol`.',
    scenario:
      'The snapshot store realizes persistSnapshot under the code name writeSnapshotRow, declared in the module and mapped via the per-method symbol.',
    tree: {
      subsystems: [{ id: 'reporting', description: 'Analytics snapshots for the merchant dashboard.' }],
      components: [
        {
          id: 'snapshot-store',
          componentType: 'Store',
          subsystem: 'reporting',
          durability: 'read-through',
          description: 'Holds the persisted analytics snapshots.',
        },
      ],
      interfaces: [
        {
          id: 'isnapshot_store',
          component: 'snapshot-store',
          methods: [{ name: 'persistSnapshot', description: 'Persist one analytics snapshot row.' }],
        },
      ],
      implementations: [
        {
          id: 'snapshot_store_impl',
          contract: 'isnapshot_store',
          sourcePath: 'src/reporting/snapshot-store.ts',
          methods: [
            {
              name: 'persistSnapshot',
              symbol: 'writeSnapshotRow',
              intent: 'Persist the snapshot row transactionally; on write failure the snapshot is dropped and the failure is surfaced to the caller.',
            },
          ],
        },
      ],
      files: {
        'src/reporting/snapshot-store.ts': [
          'export function writeSnapshotRow(payload: object): void {',
          '  // upsert the snapshot row into the analytics table',
          '}',
          '',
        ].join('\n'),
      },
    },
  }),

  // -------------------------------------------------------------------------
  // UNREALIZED_METHOD — pair D: Portals default to the anchored tier, so a
  // route-registration string literal realizes the handler; with neither a
  // declaration nor a literal, even the anchored tier fires
  // -------------------------------------------------------------------------
  defineRuleFixture({
    code: 'UNREALIZED_METHOD',
    severity: 'warning',
    anchoredTo: 'payments_webhook_portal_impl',
    expectFire: true,
    scenario:
      'The payments webhook portal contract promises handlePaymentWebhook, but the routes module neither declares the handler nor registers it by name — even the Portal\'s lenient anchored default finds nothing.',
    tree: {
      subsystems: [{ id: 'payments', description: 'Payment capture and provider webhook intake.' }],
      components: [
        {
          id: 'payments-webhook-portal',
          componentType: 'Portal',
          portalType: 'HTTP_API',
          subsystem: 'payments',
          description: 'Receives asynchronous payment status webhooks from the PSP.',
        },
      ],
      interfaces: [
        {
          id: 'ipayments_webhook_portal',
          component: 'payments-webhook-portal',
          methods: [{ name: 'handlePaymentWebhook', description: 'Accept and verify one PSP webhook delivery.' }],
        },
      ],
      implementations: [
        {
          id: 'payments_webhook_portal_impl',
          contract: 'ipayments_webhook_portal',
          sourcePath: 'src/payments/webhook-routes.ts',
          methods: [
            {
              name: 'handlePaymentWebhook',
              narrative: [{ stepNumber: 1, type: 'local', description: 'Verify the webhook signature and enqueue the status update.' }],
            },
          ],
        },
      ],
      files: {
        'src/payments/webhook-routes.ts': [
          'export const webhookRouter = createRouter();',
          '',
          'function createRouter(): object {',
          '  return {};',
          '}',
          '',
        ].join('\n'),
      },
    },
  }),
  defineRuleFixture({
    code: 'UNREALIZED_METHOD',
    expectFire: false,
    reason:
      'Portals default to the anchored tier, and the documented anchored tier accepts an exact string-literal occurrence — the route registration names the handler.',
    scenario:
      'The payments webhook portal registers handlePaymentWebhook by name in its route table, which the Portal stereotype\'s anchored default accepts.',
    tree: {
      subsystems: [{ id: 'payments', description: 'Payment capture and provider webhook intake.' }],
      components: [
        {
          id: 'payments-webhook-portal',
          componentType: 'Portal',
          portalType: 'HTTP_API',
          subsystem: 'payments',
          description: 'Receives asynchronous payment status webhooks from the PSP.',
        },
      ],
      interfaces: [
        {
          id: 'ipayments_webhook_portal',
          component: 'payments-webhook-portal',
          methods: [{ name: 'handlePaymentWebhook', description: 'Accept and verify one PSP webhook delivery.' }],
        },
      ],
      implementations: [
        {
          id: 'payments_webhook_portal_impl',
          contract: 'ipayments_webhook_portal',
          sourcePath: 'src/payments/webhook-routes.ts',
          methods: [
            {
              name: 'handlePaymentWebhook',
              narrative: [{ stepNumber: 1, type: 'local', description: 'Verify the webhook signature and enqueue the status update.' }],
            },
          ],
        },
      ],
      files: {
        'src/payments/webhook-routes.ts': [
          'export const webhookRouter = createRouter();',
          '',
          'webhookRouter.post(\'/psp/status\', \'handlePaymentWebhook\');',
          '',
          'function createRouter(): { post: (route: string, handler: string) => void } {',
          '  return { post: () => undefined };',
          '}',
          '',
        ].join('\n'),
      },
    },
  }),

  // -------------------------------------------------------------------------
  // UNREALIZED_METHOD — control E: the `off` tier skips method checks for
  // generated/vendored code (the sourcePath existence check still applied)
  // -------------------------------------------------------------------------
  defineRuleFixture({
    code: 'UNREALIZED_METHOD',
    expectFire: false,
    reason:
      'The documented `off` tier exists exactly for generated/vendored code: method checks are skipped, only the sourcePath existence check applies.',
    scenario:
      'The ERP sync adapter wraps a vendor-generated client module whose symbols never match the contract, so its implementation dials conformance off.',
    tree: {
      subsystems: [{ id: 'integrations', description: 'Outbound synchronization with the merchant\'s ERP.' }],
      components: [
        {
          id: 'erp-sync-adapter',
          componentType: 'Adapter',
          subsystem: 'integrations',
          description: 'Pushes order documents into the external ERP.',
        },
      ],
      interfaces: [
        {
          id: 'ierp_sync_adapter',
          component: 'erp-sync-adapter',
          methods: [{ name: 'pushOrderDocument', description: 'Push one order document into the ERP.' }],
        },
      ],
      implementations: [
        {
          id: 'erp_sync_adapter_impl',
          contract: 'ierp_sync_adapter',
          sourcePath: 'src/integrations/erp-client.generated.ts',
          conformance: 'off',
          methods: [
            {
              name: 'pushOrderDocument',
              narrative: [{ stepNumber: 1, type: 'local', description: 'Map the order to the ERP document schema and send it.' }],
            },
          ],
        },
      ],
      files: {
        'src/integrations/erp-client.generated.ts': [
          '// AUTO-GENERATED ERP SOAP client — regenerate with npm run gen:erp',
          'export function soapOperation_42(payload: object): object {',
          '  return payload;',
          '}',
          '',
        ].join('\n'),
      },
    },
  }),

  // -------------------------------------------------------------------------
  // CONFORMANCE_ANALYSIS_SKIPPED
  // -------------------------------------------------------------------------
  defineRuleFixture({
    code: 'CONFORMANCE_ANALYSIS_SKIPPED',
    severity: 'warning',
    anchoredTo: 'barcode_decoder_impl',
    expectFire: true,
    scenario:
      'The barcode decoder implementation points at the compiled native addon binary instead of its TypeScript wrapper, so the file cannot be analyzed as source text.',
    tree: {
      subsystems: [{ id: 'warehouse', description: 'Scanning and putaway flows on the warehouse floor.' }],
      components: [
        {
          id: 'barcode-decoder',
          componentType: 'Adapter',
          subsystem: 'warehouse',
          description: 'Decodes scanner frames into GTIN barcodes.',
        },
      ],
      interfaces: [
        {
          id: 'ibarcode_decoder',
          component: 'barcode-decoder',
          methods: [{ name: 'decodeBarcode', description: 'Decode one scanner frame into a GTIN.' }],
        },
      ],
      implementations: [
        {
          id: 'barcode_decoder_impl',
          contract: 'ibarcode_decoder',
          sourcePath: 'native/barcode-decoder.node',
          methods: [
            {
              name: 'decodeBarcode',
              narrative: [{ stepNumber: 1, type: 'local', description: 'Run the frame through the native decoding routine.' }],
            },
          ],
        },
      ],
      files: {
        // a binary blob: NUL bytes in the probe window mark it unreadable
        'native/barcode-decoder.node': 'MZ\u0000\u0003\u0000\u0004decoder\u0000section\u0000',
      },
    },
  }),
  defineRuleFixture({
    code: 'CONFORMANCE_ANALYSIS_SKIPPED',
    expectFire: false,
    reason: 'The sourcePath names the readable TypeScript wrapper, so method realization is checked normally.',
    scenario:
      'The barcode decoder implementation points at the TypeScript wrapper module around the native addon, which is readable source text.',
    tree: {
      subsystems: [{ id: 'warehouse', description: 'Scanning and putaway flows on the warehouse floor.' }],
      components: [
        {
          id: 'barcode-decoder',
          componentType: 'Adapter',
          subsystem: 'warehouse',
          description: 'Decodes scanner frames into GTIN barcodes.',
        },
      ],
      interfaces: [
        {
          id: 'ibarcode_decoder',
          component: 'barcode-decoder',
          methods: [{ name: 'decodeBarcode', description: 'Decode one scanner frame into a GTIN.' }],
        },
      ],
      implementations: [
        {
          id: 'barcode_decoder_impl',
          contract: 'ibarcode_decoder',
          sourcePath: 'src/warehouse/barcode-decoder.ts',
          methods: [
            {
              name: 'decodeBarcode',
              narrative: [{ stepNumber: 1, type: 'local', description: 'Run the frame through the native decoding routine.' }],
            },
          ],
        },
      ],
      files: {
        'src/warehouse/barcode-decoder.ts': [
          'export function decodeBarcode(frame: Uint8Array): string {',
          '  return \'0012345678905\';',
          '}',
          '',
        ].join('\n'),
      },
    },
  }),

  // -------------------------------------------------------------------------
  // CONFORMANCE_DEGRADED
  // -------------------------------------------------------------------------
  defineRuleFixture({
    code: 'CONFORMANCE_DEGRADED',
    severity: 'warning',
    expectFire: true,
    scenario:
      'A machine-generated fare rule decision matrix is nested beyond what the compiler front-end can parse, so that TypeScript file is honestly analyzed below exact grade and dependency conformance must skip it.',
    tree: {
      subsystems: [{ id: 'pricing', description: 'Fare computation for the booking flow.' }],
      components: [
        {
          id: 'fare-rules-engine',
          componentType: 'Specialist',
          subsystem: 'pricing',
          description: 'Evaluates the generated fare rule matrix for a booking.',
        },
      ],
      interfaces: [
        {
          id: 'ifare_rules_engine',
          component: 'fare-rules-engine',
          methods: [{ name: 'evaluateFareRules', description: 'Evaluate the fare rule matrix for one booking.' }],
        },
      ],
      implementations: [
        {
          id: 'fare_rules_engine_impl',
          contract: 'ifare_rules_engine',
          sourcePath: 'src/pricing/fare-rules.generated.ts',
          methods: [
            {
              name: 'evaluateFareRules',
              narrative: [{ stepNumber: 1, type: 'local', description: 'Walk the decision matrix and produce the fare adjustments.' }],
            },
          ],
        },
      ],
      files: {
        'src/pricing/fare-rules.generated.ts': GENERATED_FARE_MATRIX,
      },
    },
  }),
  defineRuleFixture({
    code: 'CONFORMANCE_DEGRADED',
    expectFire: false,
    reason: 'The generated module parses normally, so every TypeScript file reaches exact grade and nothing is degraded.',
    scenario:
      'The fare rule decision matrix is generated in a shallow, parseable form and the compiler analyzes it at exact grade.',
    tree: {
      subsystems: [{ id: 'pricing', description: 'Fare computation for the booking flow.' }],
      components: [
        {
          id: 'fare-rules-engine',
          componentType: 'Specialist',
          subsystem: 'pricing',
          description: 'Evaluates the generated fare rule matrix for a booking.',
        },
      ],
      interfaces: [
        {
          id: 'ifare_rules_engine',
          component: 'fare-rules-engine',
          methods: [{ name: 'evaluateFareRules', description: 'Evaluate the fare rule matrix for one booking.' }],
        },
      ],
      implementations: [
        {
          id: 'fare_rules_engine_impl',
          contract: 'ifare_rules_engine',
          sourcePath: 'src/pricing/fare-rules.generated.ts',
          methods: [
            {
              name: 'evaluateFareRules',
              narrative: [{ stepNumber: 1, type: 'local', description: 'Walk the decision matrix and produce the fare adjustments.' }],
            },
          ],
        },
      ],
      files: {
        'src/pricing/fare-rules.generated.ts': [
          '// AUTO-GENERATED by fare-matrix-compiler v3 — do not edit by hand.',
          'export const fareRuleMatrix = [[0, 1], [1, 0]];',
          'export function evaluateFareRules(): number { return 0; }',
          '',
        ].join('\n'),
      },
    },
  }),
];
