import * as fs from 'fs';
import * as path from 'path';
import { AI_PATHS } from '../config/loader.js';

// ---------------------------------------------------------------------------
// Topology history log
//
// Appends a timestamped entry to .wai/docs/topology-history.md whenever a
// destructive topology operation (split, merge, deprecate) is performed.
// The file is created if it doesn't exist.
// ---------------------------------------------------------------------------

interface HistoryEntry {
  action: 'split' | 'merge' | 'deprecate';
  description: string;
  agentIds: string[];
}

export function appendTopologyHistory(entry: HistoryEntry): void {
  const historyPath = path.join(AI_PATHS.docsDir(), 'topology-history.md');
  const timestamp = new Date().toISOString().replace('T', ' ').slice(0, 19);

  const line = [
    `\n## ${timestamp}  [${entry.action}]`,
    '',
    entry.description,
    '',
    `Agents involved: ${entry.agentIds.map((id) => `\`${id}\``).join(', ')}`,
    '',
  ].join('\n');

  if (!fs.existsSync(historyPath)) {
    fs.writeFileSync(
      historyPath,
      `# Topology Change History\n\nAuto-generated by wairon. Records split, merge, and deprecation operations.\n`,
      'utf-8',
    );
  }

  fs.appendFileSync(historyPath, line, 'utf-8');
}
