import { describe, it, expect, afterEach } from 'vitest';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { projectConfigRepositoryAt } from '../../src/config/project-config.js';

// ---------------------------------------------------------------------------
// An upgrade must not delete committed agent files. A project.yaml written
// before rules.materializeAgentFiles existed was always materialized; while
// wairon-managed agent files are present it reads true, so the first save
// (doctor --fix) writes `true` down and the first lock keeps the files.
// ---------------------------------------------------------------------------

const roots: string[] = [];
function project(rules: string[] = []): string {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'wairon-mat-'));
  roots.push(root);
  fs.mkdirSync(path.join(root, '.wai'), { recursive: true });
  fs.writeFileSync(path.join(root, '.wai', 'project.yaml'), [
    'schemaVersion: 1.0.0', 'name: Legacy', 'targets:', '  - type: claude', '    outputDir: .claude/agents', '    enabled: true',
    ...(rules.length ? ['rules:', ...rules.map((r) => `  ${r}`)] : []),
    "createdAt: '2026-01-01T00:00:00.000Z'", "updatedAt: '2026-01-01T00:00:00.000Z'", '',
  ].join('\n'));
  return root;
}
function agentFile(root: string, dir: string, name: string, body = '# agent\n'): void {
  fs.mkdirSync(path.join(root, dir), { recursive: true });
  fs.writeFileSync(path.join(root, dir, name), body);
}

afterEach(() => {
  for (const r of roots.splice(0)) fs.rmSync(r, { recursive: true, force: true });
});

describe('materializeAgentFiles on a configuration that predates it', () => {
  it('reads true while wairon-managed agent files are present (by name)', () => {
    const root = project();
    agentFile(root, '.claude/agents', 'billing-owner.md');
    expect(projectConfigRepositoryAt(root).load()!.rules.materializeAgentFiles).toBe(true);
  });

  it('reads true for a managed file found by its marker, in any built-in target folder', () => {
    const root = project();
    agentFile(root, '.github/prompts', 'billing.prompt.md', '<!-- wairon:managed — generated by `wairon generate` -->\nbody\n');
    expect(projectConfigRepositoryAt(root).load()!.rules.materializeAgentFiles).toBe(true);
  });

  it('reads false with no managed agent file, and ignores hand-written ones', () => {
    const root = project();
    agentFile(root, '.claude/agents', 'my-notes.md', '# written by a person\n');
    expect(projectConfigRepositoryAt(root).load()!.rules.materializeAgentFiles).toBe(false);
  });

  it('a stated value always wins', () => {
    const root = project(['materializeAgentFiles: false']);
    agentFile(root, '.claude/agents', 'billing-owner.md');
    expect(projectConfigRepositoryAt(root).load()!.rules.materializeAgentFiles).toBe(false);
  });

  it('the first save writes true, not false', () => {
    const root = project();
    agentFile(root, '.claude/agents', 'billing-owner.md');
    const repo = projectConfigRepositoryAt(root);
    repo.setProjectType('library');
    const text = fs.readFileSync(path.join(root, '.wai', 'project.yaml'), 'utf8');
    expect(text).toMatch(/materializeAgentFiles: true/);
    expect(text).not.toMatch(/materializeAgentFiles: false/);
  });
});
