// ---------------------------------------------------------------------------
// AI Guide injection
//
// Injects a wairon usage guide into AI tool config files (CLAUDE.md,
// GEMINI.md) so the AI tool knows how to use wairon in this project.
//
// Injection is idempotent: the guide is wrapped in HTML comment markers and
// replaced if already present, so running it twice has no side-effects.
//
// Global scope:  ~/.claude/CLAUDE.md   or  ~/.gemini/GEMINI.md
// Local scope:   <project-root>/.claude/CLAUDE.md  or  <project-root>/.gemini/GEMINI.md
// ---------------------------------------------------------------------------

import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

export const GUIDE_MARKER_START = '<!-- wairon-guide-start -->';
export const GUIDE_MARKER_END = '<!-- wairon-guide-end -->';

// ---------------------------------------------------------------------------
// Guide content
// ---------------------------------------------------------------------------

export const GLOBAL_GUIDE_BODY = `\
## wairon — Spec-Driven Development (optional)

A project *may* use **wairon**, an optional spec-driven development (SDD) workflow.
If a \`.wai/specs/\` tree exists, the workflow is active for that project; otherwise
you can ignore wairon and work normally. wairon does not run or orchestrate AI
sessions — it *equips* yours.

### What wairon owns when active

- \`.wai/specs/\` is a typed spec tree: L0 System → L1 Subsystem → L2 Component →
  L3 Interface → L4 Implementation → L5 Narrative. It is the source of truth for
  the project's **architecture**.
- Agent files in \`.claude/agents/\` (and other tools) are **generated from the
  spec tree** — never edit them by hand. Run \`wairon generate\` to refresh them.
- \`wairon validate\` is an architecture-conformance gate: reference integrity,
  contract↔implementation method symmetry, component-stereotype dependency rules
  (e.g. Portals may not depend on Stores), and dependency-cycle detection.

### How wairon fits your session

- **Subagents:** the generated agent files (a \`system-architect\`, a \`*-owner\`
  per subsystem/domain, a \`*-implementer\` per component). Spawn them with your
  tool's own native subagent mechanism — wairon does not spawn sessions itself.
- **Skills:** \`sdd-architect\`, \`sdd-narrative\`, \`sdd-auditor\`, \`sdd-implement\` —
  run them in-session to drive the workflow.
- **MCP tools:** \`sdd_*\` tools to author and validate specs (see the project guide).

### Strict once enabled

If the SDD workflow is active, follow it strictly:
1. **Design before code.** Do not write source for a component until its spec is
   complete and \`sdd_validate_tree\` passes with zero errors.
2. **Spec is law.** Generated code maps 1:1 to the interfaces and narrative steps.
   If the spec is incomplete, stop and extend the spec — do not improvise.
3. **Human-in-the-loop.** Present each drafted spec layer for approval before
   moving on; do not design several layers ahead unprompted.

### Key commands (human-run)
\`\`\`
wairon status                spec-tree completeness dashboard
wairon validate              architecture-conformance gate
wairon generate              regenerate agent files + (re)install skills
wairon list                  list agents resolved from the spec tree
wairon domains list          list domains (subsystem-derived + free-standing)
wairon skills install        (re)install the SDD skills into your tools
wairon mcp install           register the wairon MCP server
\`\`\``;

const LOCAL_GUIDE_BODY = `\
## Agent Topology (managed by wairon)

Agent files in this project are generated by **wairon** — do not edit them directly.
The source of truth is the SDD spec tree under \`.wai/specs/\`; agents are derived
from it. Run \`wairon generate\` to refresh agent files after the specs change.

### Spec-Driven Development (SDD) Rules
This project follows a strict **Design-Before-Code** Spec-Driven Development framework:
1. **Spec File Segregation**:
   - L0 (System): Declared ONLY in \`.wai/specs/system.yaml\`.
   - L1 (Subsystems): Declared in a directory named after the subsystem under \`.wai/specs/\`, using \`subsystem.yaml\` as the reserved file name. (E.g. \`.wai/specs/billing/subsystem.yaml\`).
   - L2 (Components): Declared in a subdirectory under their parent subsystem, named after the component, using \`component.yaml\` as the reserved file name. (E.g. \`.wai/specs/billing/billing_store/component.yaml\`).
   - L3 (Interfaces): Declared in the same subdirectory as their component, using \`interface.yaml\` as the reserved file name. (E.g. \`.wai/specs/billing/billing_store/interface.yaml\`).
   - L4 (Implementations) & L5 (Narratives): Declared in the same subdirectory as their component, using \`implementation.yaml\` as the reserved file name. (E.g. \`.wai/specs/billing/billing_store/implementation.yaml\`).
   *(Note: If legacy flat folders like \`.wai/specs/subsystems/\` exist and contain files, respect them and continue placing new specs flat within those legacy folders. Otherwise, always default to the nested tree structure.)*
2. **Mandatory Iterative Feedback Loop**:
   - You must NOT generate multiple layers of specs or write any implementation code without explicit user feedback and approval at **each stage**.
   - For every spec or narrative you draft: present the drafted content (YAML format) and a concise summary of the key design choices directly in the chat/console message. Do NOT create temporary/intermediate markdown review files in the brain or workspace for the user to review.
   - Ask: "Is this correct, or is it off-track?" and get explicit approval for the current layer/stage before proceeding.
3. **No Implementation Without Design Sign-Off**:
   - Do NOT write any source code (e.g. \`.ts\`, \`.rs\`, \`.py\` etc.) for any component until the design has been finalized, validated using the \`sdd_validate_tree\` MCP tool with zero errors, and marked as \`status: complete\`.
4. **Exclusively Use MCP Tools**:
   - As an AI agent, you must ONLY use the Wairon MCP tools (\`sdd_get_status\`, \`sdd_validate_tree\`, \`sdd_initialize_system\`, \`sdd_add_subsystem\`, \`sdd_add_component\`, \`sdd_define_interface\`, \`sdd_write_narrative\`) to perform system status checks, validations, and design updates.
   - Do NOT execute CLI shell commands in the terminal (e.g. \`wairon status\`, \`wairon validate\`, \`wairon init\`). Those terminal commands are strictly reserved for the human developer.
5. **Mandatory Sub-Agent Task Delegation**:
   - You must NOT perform design updates, write method narratives, or generate component implementation source code directly yourself in the root context.
   - For all L0–L3 spec design, delegate to the **\`system-architect\`** subagent (or invoke the \`/sdd architect\` skill).
   - For all L4–L5 narrative design, delegate to the **\`sdd-narrative\`** subagent (or invoke the \`/sdd narrative\` skill).
   - For compiling specs to code (Stage 6 implementation), spawn the specific **\`<component-id>-implementer\`** subagent using your tool's native subagent mechanism (e.g. the Task tool / \`@agent\`). wairon does not spawn sessions itself.
   - Always let the specialized subagents make file changes and report back.

### Quick Reference (For Human Developers)
\`\`\`
wairon status                spec-tree completeness dashboard
wairon validate              architecture-conformance gate
wairon generate              regenerate agent files + (re)install skills
wairon list                  list agents resolved from the spec tree
wairon domains list          list domains (subsystem-derived + free-standing)
\`\`\``;

// ---------------------------------------------------------------------------
// Path resolution
// ---------------------------------------------------------------------------

export function globalGuideFilePath(targetType: string): string | null {
  // Respect custom config dirs (account aliases) — same as MCP install.
  if (targetType === 'claude') return path.join(process.env['CLAUDE_CONFIG_DIR'] || path.join(os.homedir(), '.claude'), 'CLAUDE.md');
  if (targetType === 'gemini') return path.join(process.env['GEMINI_CONFIG_DIR'] || path.join(os.homedir(), '.gemini'), 'GEMINI.md');
  return null;
}

export function localGuideFilePath(projectRoot: string, targetType: string): string | null {
  if (targetType === 'claude') return path.join(projectRoot, '.claude', 'CLAUDE.md');
  if (targetType === 'gemini' || targetType === 'agy') return path.join(projectRoot, '.gemini', 'GEMINI.md');
  return null;
}

// ---------------------------------------------------------------------------
// Detect / inject
// ---------------------------------------------------------------------------

/** Returns true if the file exists and already contains the wairon guide. */
export function hasWaironGuide(filePath: string): boolean {
  if (!fs.existsSync(filePath)) return false;
  return fs.readFileSync(filePath, 'utf-8').includes(GUIDE_MARKER_START);
}

/**
 * Inject (or update) the wairon guide section in the given file.
 * Creates the file and any parent directories if they don't exist.
 */
export function injectGuide(filePath: string, scope: 'global' | 'local'): void {
  const body = scope === 'global' ? GLOBAL_GUIDE_BODY : LOCAL_GUIDE_BODY;
  const command = getCliCommandString();
  const customizedBody = body.replace(/\bwairon\b/g, command);
  const section = `\n\n${GUIDE_MARKER_START}\n${customizedBody}\n${GUIDE_MARKER_END}\n`;

  const existing = fs.existsSync(filePath)
    ? fs.readFileSync(filePath, 'utf-8')
    : '';

  const stripped = stripGuideSection(existing);
  const newContent = stripped.trimEnd() + section;

  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, newContent, 'utf-8');
}

/** Remove the wairon guide section from a string (for clean replacement). */
export function stripGuideSection(content: string): string {
  const start = content.indexOf(GUIDE_MARKER_START);
  const end = content.indexOf(GUIDE_MARKER_END);
  if (start === -1 || end === -1) return content;
  return content.slice(0, start) + content.slice(end + GUIDE_MARKER_END.length);
}

export function writeRootGuideDelegator(projectRoot: string, targetType: string): void {
  if (targetType === 'claude') {
    const filePath = path.join(projectRoot, 'CLAUDE.md');
    const content = `@.claude/CLAUDE.md
@.claude/skills/sdd-architect.md
@.claude/skills/sdd-narrative.md
@.claude/skills/sdd-auditor.md
@.claude/skills/sdd-implement.md

# Wairon SDD Project

This project uses the Wairon Spec-Driven Development (SDD) framework. 
To start designing or modifying the system, you must invoke the **\`/sdd-architect\`** sub-agent.

Refer to [.claude/CLAUDE.md](.claude/CLAUDE.md) for full instructions and CLI references.
`;
    fs.writeFileSync(filePath, content, 'utf-8');
  } else if (targetType === 'gemini' || targetType === 'agy') {
    const filePath = path.join(projectRoot, 'GEMINI.md');
    const content = `@.gemini/GEMINI.md
@.gemini/skills/sdd-architect.md
@.gemini/skills/sdd-narrative.md
@.gemini/skills/sdd-auditor.md
@.gemini/skills/sdd-implement.md

# Wairon SDD Project

This project uses the Wairon Spec-Driven Development (SDD) framework. 
To start designing the system, invoke the **\`sdd-architect\`** skill.

Refer to [.gemini/GEMINI.md](.gemini/GEMINI.md) for full instructions and CLI references.
`;
    fs.writeFileSync(filePath, content, 'utf-8');
  } else if (targetType === 'cursor') {
    const filePath = path.join(projectRoot, '.cursorrules');
    const content = `# Wairon SDD Project

This project uses the Wairon Spec-Driven Development (SDD) framework.

Refer to the rules in [.cursor/rules/](.cursor/rules/) for full instructions and CLI references.
`;
    fs.writeFileSync(filePath, content, 'utf-8');
  } else if (targetType === 'copilot') {
    const filePath = path.join(projectRoot, '.github', 'copilot-instructions.md');
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    const content = `# Wairon SDD Project

This project uses the Wairon Spec-Driven Development (SDD) framework.

Refer to the prompts in [.github/prompts/](.github/prompts/) for instructions and CLI references.
`;
    fs.writeFileSync(filePath, content, 'utf-8');
  } else if (targetType === 'codex') {
    const filePath = path.join(projectRoot, '.codexrules');
    const content = `# Wairon SDD Project

Refer to [.codex/agents/](.codex/agents/) for full instructions and CLI references.
`;
    fs.writeFileSync(filePath, content, 'utf-8');
  }
}

export function getCliCommandString(): string {
  const scriptPath = process.argv[1] ? path.resolve(process.argv[1]).replace(/\\/g, '/') : null;
  const useDirectNode = scriptPath && (scriptPath.endsWith('.js') || scriptPath.endsWith('.ts'));
  return useDirectNode ? `node "${scriptPath}"` : 'wairon';
}
