import { aiDir, writeFile, writeFileIfChanged, readFileOrNull, pathExists } from '../utils/fs.js';
import { GLOBAL_GUIDE_BODY } from '../utils/ai-guide.js';
import { versionStamp } from './stamp.js';

// ---------------------------------------------------------------------------
// Context — shared project context under .wai/context/
//
// .wai/context/
//   project.md        ← human-edited: project description, stack, conventions
//   architecture.md   ← human-edited: system design notes (optional)
//   domains.md        ← auto-generated: domain list from registry
//   wairon-guide.md   ← auto-generated: importable reference for AI tools
//
// The generated files are rebuilt by syncContextFiles() which is called by
// `wairon generate` and `wairon init`.
// ---------------------------------------------------------------------------

export function contextDir(...segments: string[]): string {
  return aiDir('context', ...segments);
}

export const CONTEXT_PATHS = {
  dir:           () => contextDir(),
  projectMd:     () => contextDir('project.md'),
  architectureMd:() => contextDir('architecture.md'),
  domainsMd:     () => contextDir('domains.md'),
  waironGuideMd: () => contextDir('wairon-guide.md'),
} as const;

// ---------------------------------------------------------------------------
// Presence checks
// ---------------------------------------------------------------------------

export function hasContext(): boolean {
  return pathExists(CONTEXT_PATHS.projectMd());
}

export function hasArchitectureContext(): boolean {
  return pathExists(CONTEXT_PATHS.architectureMd());
}

// ---------------------------------------------------------------------------
// Raw reads / writes (human-edited files)
// ---------------------------------------------------------------------------

export function readProjectContext(): string | null {
  return readFileOrNull(CONTEXT_PATHS.projectMd());
}

export function readArchitectureContext(): string | null {
  return readFileOrNull(CONTEXT_PATHS.architectureMd());
}

export function writeProjectContext(content: string): void {
  writeFile(CONTEXT_PATHS.projectMd(), content);
}

export function writeArchitectureContext(content: string): void {
  writeFile(CONTEXT_PATHS.architectureMd(), content);
}

// ---------------------------------------------------------------------------
// Renderers for auto-generated files
// ---------------------------------------------------------------------------

/**
 * Build domains.md from the current domain registry.
 * Imported lazily to avoid circular deps at module load time.
 */
export function renderDomainsDoc(): string {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { resolveDomains } = require('./domains.js') as typeof import('./domains.js');
  const domains = resolveDomains();

  const today = new Date().toISOString().split('T')[0];
  const lines: string[] = [
    versionStamp(),
    `# Domains`,
    ``,
    `> Auto-generated by wairon. The human developer rebuilds this with \`wairon generate\`.  `,
    `> Last updated: ${today}`,
    ``,
  ];

  if (domains.length === 0) {
    lines.push('_No domains yet. Define subsystems in the spec tree, or add free-standing domains with `wairon domains add`._');
  } else {
    lines.push(`**${domains.length} domain(s).**`);
    lines.push('');
    lines.push('| ID | Name | Source | Owned paths |');
    lines.push('|----|------|--------|-------------|');
    for (const d of domains) {
      const name = d.name ?? d.id;
      const source = d.boundTo ? `subsystem \`${d.boundTo}\`` : 'free-standing';
      lines.push(`| \`${d.id}\` | ${name} | ${source} | \`${d.ownedPaths.join('`, `') || '—'}\` |`);
    }
  }

  return lines.join('\n') + '\n';
}

/**
 * Build wairon-guide.md — the file AI tools can @-import for full wairon
 * awareness. Contains: project context + domain map + wairon usage guide.
 */
export function renderWaironGuide(): string {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { loadProjectConfig } = require('../config/loader.js') as typeof import('../config/loader.js');
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { resolveDomains } = require('./domains.js') as typeof import('./domains.js');

  const domains = resolveDomains();

  let projectName = 'this project';
  try {
    projectName = loadProjectConfig().name;
  } catch { /* not initialized or broken — use fallback */ }

  const projectCtx = readProjectContext();
  const archCtx = readArchitectureContext();

  const lines: string[] = [
    versionStamp(),
    `<!-- wairon-generated — do not edit directly; the human developer rebuilds this with \`wairon generate\` -->`,
    ``,
  ];

  // Project context block
  if (projectCtx) {
    lines.push(`# Project Context — ${projectName}`);
    lines.push('');
    lines.push(projectCtx.trim());
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  // Architecture block
  if (archCtx) {
    lines.push('# Architecture');
    lines.push('');
    lines.push(archCtx.trim());
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  // Domain map
  lines.push(`# Domain Map (${domains.length} domain${domains.length !== 1 ? 's' : ''})`);
  lines.push('');
  if (domains.length === 0) {
    lines.push('_No domains yet._');
  } else {
    lines.push('| ID | Source | Name |');
    lines.push('|----|--------|------|');
    for (const d of domains) {
      const name = d.name ?? d.id;
      const source = d.boundTo ? `subsystem \`${d.boundTo}\`` : 'free-standing';
      lines.push(`| \`${d.id}\` | ${source} | ${name} |`);
    }
  }
  lines.push('');
  lines.push('---');
  lines.push('');

  // MCP server note (when installed in this project's .claude/settings.json)
  const mcpSettingsPath = require('path').join(process.cwd(), '.claude', 'settings.json');
  let mcpInstalled = false;
  try {
    const s = JSON.parse(require('fs').readFileSync(mcpSettingsPath, 'utf8'));
    mcpInstalled = !!(s?.mcpServers?.wairon);
  } catch { /* not installed */ }

  if (mcpInstalled) {
    lines.push('# wairon MCP Tools');
    lines.push('');
    lines.push('The **wairon MCP server** is active in this project. You can call these tools directly:');
    lines.push('');
    lines.push('| Tool | Purpose |');
    lines.push('|------|---------|');
    lines.push('| `listAgents` | List agents resolved from the spec tree (optionally filter by domainId) |');
    lines.push('| `getAgent` | Get full details of an agent by id |');
    lines.push('| `listDomains` | List domains (subsystem-derived + free-standing) |');
    lines.push('| `validateTopology` | Check for topology errors/warnings |');
    lines.push('| `getProjectConfig` | Get the project configuration |');
    lines.push('| `sdd_initialize_system` | Create the L0 system spec |');
    lines.push('| `sdd_add_subsystem` | Add an L1 subsystem |');
    lines.push('| `sdd_add_component` | Add an L2 component |');
    lines.push('| `sdd_define_interface` | Define an L3 interface contract |');
    lines.push('| `sdd_write_narrative` | Write an L4 implementation + L5 narrative |');
    lines.push('| `sdd_validate_tree` | Validate the whole spec tree |');
    lines.push('| `sdd_get_status` | Spec-tree completeness dashboard |');
    lines.push('');
    lines.push('Use these MCP tools to query and change project state — never the `wairon` CLI (that is the human developer\'s tool).');
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  // Full wairon usage guide
  lines.push(GLOBAL_GUIDE_BODY);
  lines.push('');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Sync: rebuild all auto-generated context files
// ---------------------------------------------------------------------------

export interface SyncResult {
  domainsUpdated: boolean;
  guideUpdated: boolean;
}

/**
 * Regenerate domains.md and wairon-guide.md from the current registry state.
 * Called by `wairon generate` and `wairon init`.
 */
export function syncContextFiles(): SyncResult {
  const domainsContent  = renderDomainsDoc();
  const guideContent    = renderWaironGuide();

  const domainsUpdated  = writeFileIfChanged(CONTEXT_PATHS.domainsMd(),     domainsContent);
  const guideUpdated    = writeFileIfChanged(CONTEXT_PATHS.waironGuideMd(),  guideContent);

  return { domainsUpdated, guideUpdated };
}
