import { aiDir, writeFile, writeFileIfChanged, readFileOrNull, pathExists } from '../utils/fs.js';
import { GLOBAL_GUIDE_BODY } from '../utils/ai-guide.js';

// ---------------------------------------------------------------------------
// Context — shared project context under .wai/context/
//
// .wai/context/
//   project.md        ← human-edited: project description, stack, conventions
//   architecture.md   ← human-edited: system design notes (optional)
//   domains.md        ← auto-generated: domain list from registry
//   wairon-guide.md   ← auto-generated: importable reference for AI tools
//
// The generated files are rebuilt by syncContextFiles() which is called by
// `wairon context sync` and automatically by `wairon generate`.
// ---------------------------------------------------------------------------

export function contextDir(...segments: string[]): string {
  return aiDir('context', ...segments);
}

export const CONTEXT_PATHS = {
  dir:           () => contextDir(),
  projectMd:     () => contextDir('project.md'),
  architectureMd:() => contextDir('architecture.md'),
  domainsMd:     () => contextDir('domains.md'),
  waironGuideMd: () => contextDir('wairon-guide.md'),
} as const;

// ---------------------------------------------------------------------------
// Presence checks
// ---------------------------------------------------------------------------

export function hasContext(): boolean {
  return pathExists(CONTEXT_PATHS.projectMd());
}

export function hasArchitectureContext(): boolean {
  return pathExists(CONTEXT_PATHS.architectureMd());
}

// ---------------------------------------------------------------------------
// Raw reads / writes (human-edited files)
// ---------------------------------------------------------------------------

export function readProjectContext(): string | null {
  return readFileOrNull(CONTEXT_PATHS.projectMd());
}

export function readArchitectureContext(): string | null {
  return readFileOrNull(CONTEXT_PATHS.architectureMd());
}

export function writeProjectContext(content: string): void {
  writeFile(CONTEXT_PATHS.projectMd(), content);
}

export function writeArchitectureContext(content: string): void {
  writeFile(CONTEXT_PATHS.architectureMd(), content);
}

// ---------------------------------------------------------------------------
// Renderers for auto-generated files
// ---------------------------------------------------------------------------

/**
 * Build domains.md from the current domain registry.
 * Imported lazily to avoid circular deps at module load time.
 */
export function renderDomainsDoc(): string {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { loadDomainRegistry } = require('../config/loader.js') as typeof import('../config/loader.js');
  const registry = loadDomainRegistry();
  const domains = registry.domains;

  const today = new Date().toISOString().split('T')[0];
  const lines: string[] = [
    `# Domains`,
    ``,
    `> Auto-generated by wairon. Run \`wairon context sync\` to update.  `,
    `> Last updated: ${today}`,
    ``,
  ];

  if (domains.length === 0) {
    lines.push('_No domains tracked yet. Run `wairon domains scan --add` to add domains._');
  } else {
    lines.push(`**${domains.length} domain(s) tracked.**`);
    lines.push('');
    lines.push('| ID | Name | Path | Status |');
    lines.push('|----|------|------|--------|');
    for (const d of domains) {
      const name = d.name ?? d.id;
      const status = d.status ?? 'active';
      lines.push(`| \`${d.id}\` | ${name} | \`${d.path}\` | ${status} |`);
    }
  }

  return lines.join('\n') + '\n';
}

/**
 * Build wairon-guide.md — the file AI tools can @-import for full wairon
 * awareness. Contains: project context + domain map + wairon usage guide.
 */
export function renderWaironGuide(): string {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { loadDomainRegistry, loadProjectConfig } = require('../config/loader.js') as typeof import('../config/loader.js');

  const registry = loadDomainRegistry();
  const domains = registry.domains;

  let projectName = 'this project';
  try {
    projectName = loadProjectConfig().name;
  } catch { /* not initialized or broken — use fallback */ }

  const projectCtx = readProjectContext();
  const archCtx = readArchitectureContext();

  const lines: string[] = [
    `<!-- wairon-generated — do not edit directly -->`,
    `<!-- source: .wai/context/project.md — run \`wairon context sync\` to rebuild -->`,
    ``,
  ];

  // Project context block
  if (projectCtx) {
    lines.push(`# Project Context — ${projectName}`);
    lines.push('');
    lines.push(projectCtx.trim());
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  // Architecture block
  if (archCtx) {
    lines.push('# Architecture');
    lines.push('');
    lines.push(archCtx.trim());
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  // Domain map
  lines.push(`# Domain Map (${domains.length} domain${domains.length !== 1 ? 's' : ''})`);
  lines.push('');
  if (domains.length === 0) {
    lines.push('_No domains tracked yet._');
  } else {
    lines.push('| ID | Path | Name |');
    lines.push('|----|------|------|');
    for (const d of domains) {
      const name = d.name ?? d.id;
      lines.push(`| \`${d.id}\` | \`${d.path}\` | ${name} |`);
    }
  }
  lines.push('');
  lines.push('---');
  lines.push('');

  // Full wairon usage guide
  lines.push(GLOBAL_GUIDE_BODY);
  lines.push('');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Sync: rebuild all auto-generated context files
// ---------------------------------------------------------------------------

export interface SyncResult {
  domainsUpdated: boolean;
  guideUpdated: boolean;
}

/**
 * Regenerate domains.md and wairon-guide.md from the current registry state.
 * Called by `wairon context sync` and silently by `wairon generate`.
 */
export function syncContextFiles(): SyncResult {
  const domainsContent  = renderDomainsDoc();
  const guideContent    = renderWaironGuide();

  const domainsUpdated  = writeFileIfChanged(CONTEXT_PATHS.domainsMd(),     domainsContent);
  const guideUpdated    = writeFileIfChanged(CONTEXT_PATHS.waironGuideMd(),  guideContent);

  return { domainsUpdated, guideUpdated };
}
